version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/web/staticfiles
    ports:
      - 8000:8000
    environment: 
      - ./.dev
    image: tuxiboule/projet_13



volumes:
  static_volume: